### ISSUE TITLE
[RasPi4/armhf] SIGSEGV on run

### ISSUE THREAD

**Issue by SuperFromND** [Windblade-GR01/Ikemen-GO#184]
### **Error (from run to exit)**

```
pi@raspberrypi:~/ikemen_GO/bin $ sudo ./Ikemen_GO_linux 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x206894]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetIcon(0x147c230, 0x1600700, 0x1, 0x1)
	/home/pi/ikemen_GO/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:416 +0xa0
main.(*System).init(0x88e298, 0x280, 0x1e0, 0x1)
	/home/pi/ikemen_GO/src/system.go:515 +0x598
main.main()
	/home/pi/ikemen_GO/src/main.go:480 +0x16e8
pi@raspberrypi:~/ikemen_GO/bin $ 
```

### **Hardware/Software Specs**
**Hardware:** 
Raspberry Pi 4 1GB (default clockspeeds)

**Software:** 
Raspbian GNU/Linux 10 Buster (September 26, 2019 build; UNAME output: `Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux`)
Go version 1.11.6 linux/arm (as installed from `apt install`)
Master repository [`db37a95`](https://github.com/Windblade-GR01/Ikemen-GO/tree/db37a95769eb514d5263aff71275680c1426bc51)

### **Reproduction Steps**
**1.** Run `sudo apt install golang-go libgl1-mesa-dev xorg-dev libopenal1 libopenal-dev libgtk-3-dev libasound2-dev` to install all dependencies needed.  `libgtk-3-dev` and `libasound2-dev` aren't specified by the Linux build instructions, but they do appear to be necessary as not having them installed causes `get.sh` to throw a few errors about missing `gtk3` and `alsa`.  I'm assuming that most Linux distros come with both of these lib packages installed already, and I guess Raspbian just excludes them.  `git` is already installed by default in Raspbian, hence why I didn't include it.

**2.** Run `git clone https://github.com/Windblade-GR01/Ikemen_GO.git`, then once it's done downloading `cd Ikemen_GO/build`.

**3.** Run `bash ./get.sh`.  Just running `./get.sh` by itself will cause an error due to lacking permissions (or at least, it did for me).  Running it through `bash` fixes this (though I suppose you could also just recursively `chmod` the entire `Ikemen_GO` directory before you `cd` into it and save some hassle).

**4.** Run `bash ./build.sh`.  I had a minor issue with this script where it tries to copy the nonexistent `/Ikemen_GO/script/` directory to `/Ikemen_GO/bin/script` due to what appears to be a syntax error.  (This can be fixed by changing the command to `cp -r ./external/script/ ./bin/script/`)

**5.** Attempt to execute the game, either with the .command file or directly with the command like (as I did in my test), and observe the results.  For me, a blank (meaning the window's contents are transparent, not just pure black) Raspbian window opens, and then immediately closes before printing the above error to the command line.

### Notes / Miscellaneous
This does not appear to be related to issue #8 , as they were able to at least start the engine before a crash occured, whereas this crashes nearly immediately.

This crash occurs both with and without the `vc4-fkms-v3d` option in `/boot/config.txt`.

Reading the error, it mentions mainly a GLFW library in Go-GL, so perhaps this is an issue with them and not Ikemen?  Hard to say though; their Github page doesn't have any issues that mention `window.go` being broken.

**Comment by SuperFromND** [comment]
Alright, I've managed to figure out what was causing this error!  The game was trying to find the icon file at the directory `bin/external/icons/`, but since the `icons` folder wasn't getting copied to `bin/` (and since `/external/` wasn't either), the game couldn't find it and thus errors out (hence the "nil pointer").  Simple fix: just edit `/src/main.go` line 166 to the following:

```go
	"WindowMainIconLocation": [
		"icons/IkemenCylia.png"
	]
```

And then add this line to `/build/build.sh`:

```bash
cp -r ./external/icons/ ./bin/icons/
```

...unfortunately, this does *not* fix Ikemen on the Pi, as now we run into a much longer SIGSEGV:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd885de30af9df9ee pc=0x7fbd059d34]

runtime stack:
runtime.throw(0x955326, 0x2a)
	/usr/lib/go-1.11/src/runtime/panic.go:608 +0x4c
runtime.sigpanic()
	/usr/lib/go-1.11/src/runtime/signal_unix.go:374 +0x2a4

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x812d68, 0x40000b1958, 0x53)
	/usr/lib/go-1.11/src/runtime/cgocall.go:128 +0x48 fp=0x40000b1920 sp=0x40000b18f0 pc=0x44a0d0
github.com/sqweek/dialog._Cfunc_msgdlg(0x0, 0x300000000, 0x1, 0x2c503ba0, 0x0)
	_cgo_gotypes.go:401 +0x3c fp=0x40000b1950 sp=0x40000b1920 pc=0x60ab34
github.com/sqweek/dialog.runMsgDlg(0x938588, 0x5, 0x300000000, 0x1, 0x40000870e0, 0x4000000000)
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:34 +0x80 fp=0x40000b19c0 sp=0x40000b1950 pc=0x60ad98
github.com/sqweek/dialog.(*MsgBuilder).error(0x40000870e0)
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:51 +0x48 fp=0x40000b1a00 sp=0x40000b19c0 pc=0x60af10
github.com/sqweek/dialog.(*MsgBuilder).Error(0x40000870e0)
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs.go:61 +0x20 fp=0x40000b1a10 sp=0x40000b1a00 pc=0x60a698
main.main()
	/home/pi/Desktop/Stuff/Ikemen-GO/src/main.go:487 +0x20d8 fp=0x40000b1f90 sp=0x40000b1a10 pc=0x74e190
runtime.main()
	/usr/lib/go-1.11/src/runtime/proc.go:201 +0x204 fp=0x40000b1fd0 sp=0x40000b1f90 pc=0x47099c
runtime.goexit()
	/usr/lib/go-1.11/src/runtime/asm_arm64.s:1114 +0x4 fp=0x40000b1fd0 sp=0x40000b1fd0 pc=0x49898c

goroutine 19 [sleep]:
time.Sleep(0x989680)
	/usr/lib/go-1.11/src/runtime/time.go:105 +0x11c
main.(*System).soundWrite(0xce34e0)
	/home/pi/Desktop/Stuff/Ikemen-GO/src/system.go:638 +0x2bc
created by main.(*System).audioOpen
	/home/pi/Desktop/Stuff/Ikemen-GO/src/system.go:626 +0xac

goroutine 20 [chan send]:
io.(*pipe).Read(0x40000aa1e0, 0x4000070200, 0x100, 0x100, 0x4000232000, 0x4, 0xffffffffffffffff)
	/usr/lib/go-1.11/src/io/pipe.go:53 +0xd0
io.(*PipeReader).Read(0x4000092720, 0x4000070200, 0x100, 0x100, 0x400007f5f0, 0xcdf880, 0x40000dedd0)
	/usr/lib/go-1.11/src/io/pipe.go:127 +0x3c
bufio.(*Reader).fill(0x40000946c0)
	/usr/lib/go-1.11/src/bufio/bufio.go:100 +0xf8
bufio.(*Reader).Peek(0x40000946c0, 0x8000, 0x4000226d40, 0x0, 0x0, 0x9e8680, 0x400007c0f0)
	/usr/lib/go-1.11/src/bufio/bufio.go:132 +0x2c
github.com/hajimehoshi/oto/internal/mux.(*Mux).Read(0x40000976c0, 0x400021a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/internal/mux/mux.go:75 +0x13c
io.copyBuffer(0x9e8720, 0x400007f5c0, 0x9e8740, 0x40000976c0, 0x400021a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/io/io.go:402 +0xcc
io.Copy(0x9e8720, 0x400007f5c0, 0x9e8740, 0x40000976c0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/io/io.go:364 +0x40
github.com/hajimehoshi/oto.NewContext.func1(0x4000086dc0)
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:85 +0x44
created by github.com/hajimehoshi/oto.NewContext
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:84 +0x198

goroutine 21 [runnable]:
io.(*pipe).Write(0x40000aa1e0, 0x40001e0030, 0x44b8, 0x44b8, 0x30, 0x0, 0x0)
	/usr/lib/go-1.11/src/io/pipe.go:87 +0x124
io.(*PipeWriter).Write(0x4000092728, 0x40001e0000, 0x44e8, 0x44e8, 0x13a, 0x40001de000, 0x4000348000)
	/usr/lib/go-1.11/src/io/pipe.go:153 +0x3c
github.com/hajimehoshi/oto.(*Player).Write(0x400007f620, 0x40001e0000, 0x44e8, 0x44e8, 0x113a, 0x1, 0x0)
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/player.go:60 +0x44
github.com/faiface/beep/speaker.update()
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:129 +0x1c8
github.com/faiface/beep/speaker.Init.func1()
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:52 +0x1c
created by github.com/faiface/beep/speaker.Init
	/home/pi/Desktop/Stuff/Ikemen-GO/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:48 +0x1fc

goroutine 22 [syscall]:
syscall.Syscall(0x3f, 0x0, 0x4000356000, 0x1000, 0x0, 0x4ec128, 0x8)
	/usr/lib/go-1.11/src/syscall/asm_linux_arm64.s:9 +0x8
syscall.read(0x0, 0x4000356000, 0x1000, 0x1000, 0x4000094001, 0x0, 0x0)
	/usr/lib/go-1.11/src/syscall/zsyscall_linux_arm64.go:732 +0x44
syscall.Read(0x0, 0x4000356000, 0x1000, 0x1000, 0x7fbbfa1000, 0x57, 0x4000356000)
	/usr/lib/go-1.11/src/syscall/syscall_unix.go:172 +0x38
internal/poll.(*FD).Read(0x4000094000, 0x4000356000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:165 +0xdc
os.(*File).read(0x4000092000, 0x4000356000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/os/file_unix.go:249 +0x40
os.(*File).Read(0x4000092000, 0x4000356000, 0x1000, 0x1000, 0x1000, 0x1000, 0x0)
	/usr/lib/go-1.11/src/os/file.go:108 +0x48
bufio.(*Scanner).Scan(0x400002df50, 0x0)
	/usr/lib/go-1.11/src/bufio/scan.go:213 +0x88
main.(*System).init.func1(0xce34e0)
	/home/pi/Desktop/Stuff/Ikemen-GO/src/system.go:523 +0xb4
created by main.(*System).init
	/home/pi/Desktop/Stuff/Ikemen-GO/src/system.go:521 +0x560
```

I honestly can't figure out what exactly is causing this error, though just from skimming it may have to do with the fact I'm running the 64-bit beta Raspbian on my Pi.  I'll install the "normal" version of Raspbian and compile, and then edit this post with the results.

**Comment by Windblade-GR01** [comment]
So finally managed to get a Raspberry Pi Model 4B.
I'll test this in the upcoming days.

**Comment by DrFuff** [comment]
I managed to compile on Ubuntu for pi4 as well.  I managed to dodge the first error but I get something similar to the second error as well.  After I fixed the log by putting the files from Ikemen-GO/font into the Ikemen-GO/bin/font I got this (It also rendered a loading screen I didn't see before):
```
failed to compile #version 150 core

//vertex position
in vec2 vert;

//pass through to fragTexCoord
in vec2 vertTexCoord;

//window res
uniform vec2 resolution;

//pass to frag
out vec2 fragTexCoord;

void main() {
   // convert the rectangle from pixels to 0.0 to 1.0
   vec2 zeroToOne = vert / resolution;

   // convert from 0->1 to 0->2
   vec2 zeroToTwo = zeroToOne * 2.0;

   // convert from 0->2 to -1->+1 (clipspace)
   vec2 clipSpace = zeroToTwo - 1.0;

   fragTexCoord = vertTexCoord;

   gl_Position = vec4(clipSpace * vec2(1, -1), 0, 1);
} : 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.00 ES, and 3.00 ES
  
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x98ba98, 0x40000b6580, 0x40014c7878, 0x0, 0x0, 0x0)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1980 +0x4f0
panic(0x8e9560, 0x40005186f0)
	/usr/lib/go-1.14/src/runtime/panic.go:969 +0x11c
github.com/Windblade-GR01/glfont.LoadFont(0x4000bcd2c0, 0x23, 0x1b, 0x140, 0xf0, 0x0, 0x0, 0x0)
	/home/harrison/go/pkg/mod/github.com/!windblade-!g!r01/glfont@v0.0.0-20200825224555-fc4d8149c6a0/font.go:48 +0x304
main.loadFntTtf(0x4000a6e460, 0x4001903bc0, 0x12, 0x4000b8c202, 0x1e, 0x1b)
	/home/harrison/Ikemen-GO/src/font.go:340 +0x13c
main.loadDefInfo(0x4000a6e460, 0x4001903bc0, 0x12, 0x40014c6ec8, 0x40ffffffff)
	/home/harrison/Ikemen-GO/src/font.go:314 +0x3cc
main.loadFntV2(0x4001903bc0, 0x12, 0xffffffff, 0x895b00, 0x40014c70f8, 0x450a78)
	/home/harrison/Ikemen-GO/src/font.go:275 +0x284
main.loadFnt(0x4000639b80, 0xd, 0x40ffffffff, 0xd, 0x40014c7000, 0x67fe00)
	/home/harrison/Ikemen-GO/src/font.go:49 +0x94
main.systemScriptInit.func53(0x40000b6580, 0xffff82c13108)
	/home/harrison/Ikemen-GO/src/script.go:766 +0x74
github.com/yuin/gopher-lua.callGFunction(0x40000b6580, 0x0, 0x40003aaf40)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:202 +0x3c
github.com/yuin/gopher-lua.init.3.func26(0x40000b6580, 0x407c100403, 0x40002450a0, 0x0)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x374
github.com/yuin/gopher-lua.mainLoop(0x40000b6580, 0x40002450a0)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:31 +0xf4
github.com/yuin/gopher-lua.(*LState).callR(0x40000b6580, 0x1, 0x1, 0x17)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x1d8
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.loRequire(0x40000b6580, 0xffff82c13108)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/baselib.go:559 +0x4d8
github.com/yuin/gopher-lua.callGFunction(0x40000b6580, 0x0, 0x40002cee80)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:202 +0x3c
github.com/yuin/gopher-lua.init.3.func26(0x40000b6580, 0x407c500402, 0x4000245000, 0x0)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x374
github.com/yuin/gopher-lua.mainLoop(0x40000b6580, 0x4000245000)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:31 +0xf4
github.com/yuin/gopher-lua.(*LState).callR(0x40000b6580, 0x0, 0xffffffffffffffff, 0x0)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x1d8
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0x40000b6580, 0x0, 0xffffffffffffffff, 0x0, 0xa45f20, 0x4000293840)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0xfc
github.com/yuin/gopher-lua.(*LState).DoFile(0x40000b6580, 0x40000c6940, 0x18, 0x0, 0x0)
	/home/harrison/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/auxlib.go:396 +0x9c
main.main()
	/home/harrison/Ikemen-GO/src/main.go:588 +0x13ec

stack traceback:
	[G]: in function 'fontNew'
	external/script/main.lua:400: in function <external/script/main.lua:375>
	(tailcall): ?
	./external/script/menu.lua:374: in function <./external/script/menu.lua:0>
	[G]: in function 'require'
	external/script/main.lua:2122: in main chunk
	[G]: ?
```
Here's my command line error **after** I moved the text for the log
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xffff80931030]

runtime stack:
runtime.throw(0x983a42, 0x2a)
	/usr/lib/go-1.14/src/runtime/panic.go:1116 +0x54
runtime.sigpanic()
	/usr/lib/go-1.14/src/runtime/signal_unix.go:679 +0x448

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8473b0, 0x40012937c8, 0x1)
	/usr/lib/go-1.14/src/runtime/cgocall.go:133 +0x50 fp=0x4001293790 sp=0x4001293750 pc=0x44a7f8
github.com/sqweek/dialog._Cfunc_gtk_dialog_run(0x24ac2340, 0x0)
	_cgo_gotypes.go:229 +0x44 fp=0x40012937c0 sp=0x4001293790 pc=0x622b7c
github.com/sqweek/dialog.runMsgDlg.func4(0x24ac2340, 0x24ae52c0)
	/home/harrison/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:39 +0x44 fp=0x40012937f0 sp=0x40012937c0 pc=0x62350c
github.com/sqweek/dialog.runMsgDlg(0x965ea0, 0x5, 0x300000000, 0x1, 0x4001293c40, 0x4000000000)
	/home/harrison/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:39 +0x158 fp=0x4001293890 sp=0x40012937f0 pc=0x6231d0
github.com/sqweek/dialog.(*MsgBuilder).error(...)
	/home/harrison/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:51
github.com/sqweek/dialog.(*MsgBuilder).Error(...)
	/home/harrison/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs.go:61
main.main()
	/home/harrison/Ikemen-GO/src/main.go:594 +0x20b4 fp=0x4001293f70 sp=0x4001293890 pc=0x76e8ac
runtime.main()
	/usr/lib/go-1.14/src/runtime/proc.go:203 +0x20c fp=0x4001293fd0 sp=0x4001293f70 pc=0x47a424
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_arm64.s:1148 +0x4 fp=0x4001293fd0 sp=0x4001293fd0 pc=0x4a691c

goroutine 5 [sleep]:
time.Sleep(0x989680)
	/usr/lib/go-1.14/src/runtime/time.go:188 +0xc0
main.(*System).soundWrite(0xd36a00)
	/home/harrison/Ikemen-GO/src/system.go:661 +0x380
created by main.(*System).audioOpen
	/home/harrison/Ikemen-GO/src/system.go:649 +0xb8

goroutine 6 [syscall]:
github.com/hajimehoshi/oto._Cfunc_snd_pcm_writei(0x247f7dc0, 0x4000ecc000, 0x5be, 0x0)
	_cgo_gotypes.go:173 +0x44
github.com/hajimehoshi/oto.(*driver).TryWrite.func1(0x4000056040, 0x4000300000)
	/home/harrison/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/driver_linux.go:143 +0xbc
github.com/hajimehoshi/oto.(*driver).TryWrite(0x4000056040, 0x40003000b8, 0x48, 0x7f48, 0x0, 0x0, 0x0)
	/home/harrison/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/driver_linux.go:143 +0x174
github.com/hajimehoshi/oto.(*driverWriter).Write(0x400007e000, 0x4000300000, 0x100, 0x8000, 0x0, 0x0, 0x0)
	/home/harrison/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:148 +0xe0
io.copyBuffer(0xa45e60, 0x400007e000, 0xa45e80, 0x4000056080, 0x4000300000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.14/src/io/io.go:407 +0x1a0
io.Copy(...)
	/usr/lib/go-1.14/src/io/io.go:364
github.com/hajimehoshi/oto.NewContext.func1(0x400000e060)
	/home/harrison/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:85 +0x58
created by github.com/hajimehoshi/oto.NewContext
	/home/harrison/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:84 +0x21c

goroutine 7 [select]:
io.(*pipe).Write(0x4000058060, 0x400006d740, 0x2da8, 0x2da8, 0x1740, 0x0, 0x0)
	/usr/lib/go-1.14/src/io/pipe.go:94 +0x158
io.(*PipeWriter).Write(0x4000010030, 0x400006c000, 0x44e8, 0x44e8, 0x113a, 0x1, 0x0)
	/usr/lib/go-1.14/src/io/pipe.go:163 +0x44
github.com/hajimehoshi/oto.(*Player).Write(...)
	/home/harrison/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/player.go:60
github.com/faiface/beep/speaker.update()
	/home/harrison/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:129 +0x1fc
github.com/faiface/beep/speaker.Init.func1()
	/home/harrison/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:52 +0x24
created by github.com/faiface/beep/speaker.Init
	/home/harrison/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:48 +0x210

goroutine 8 [syscall]:
syscall.Syscall(0x3f, 0x0, 0x4000400000, 0x1000, 0x4000406d08, 0x503cd8, 0x800000)
	/usr/lib/go-1.14/src/syscall/asm_linux_arm64.s:9 +0x10
syscall.read(0x0, 0x4000400000, 0x1000, 0x1000, 0x0, 0x1, 0x1)
	/usr/lib/go-1.14/src/syscall/zsyscall_linux_arm64.go:686 +0x4c
syscall.Read(...)
	/usr/lib/go-1.14/src/syscall/syscall_unix.go:189
internal/poll.(*FD).Read(0x400012c000, 0x4000400000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.14/src/internal/poll/fd_unix.go:165 +0xfc
os.(*File).read(...)
	/usr/lib/go-1.14/src/os/file_unix.go:263
os.(*File).Read(0x400012a000, 0x4000400000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.14/src/os/file.go:116 +0x60
bufio.(*Scanner).Scan(0x4000406f48, 0x0)
	/usr/lib/go-1.14/src/bufio/scan.go:213 +0x94
main.(*System).init.func1(0xd36a00)
	/home/harrison/Ikemen-GO/src/system.go:546 +0xdc
created by main.(*System).init
	/home/harrison/Ikemen-GO/src/system.go:544 +0x578
```
Unfortunatly, I didn't think to capture the other error so it can't confirm its the exact same as RasPi OS.

**Comment by SuperFromND** [comment]
Congrats on getting it to display the loading text, Fuff!  That's the most progress on the Pi I've seen so far, at least on this repo of IKEMEN.

I was looking around the issues and noticed #222 (which seems to have issues compiling on Ubuntu that traced back to missing files), so it's possible this might be related?  I'll test their steps and see if anything changes.

**Comment by SuperFromND** [comment]
Took a few months away from this and came back, so here's how things went:

Firstly, something I neglected to mention in the OP: for some reason, Raspbian is not recognized as linux in `build.sh` or `build_cmpt.sh` and thus the build script fails to even run initially.  My method of fixing it is by simply setting `Ikemen_GO_linux` as the default condition and removing the `exit 1`:

```sh
case "$OSTYPE" in
	darwin*)
		BINARY_NAME="Ikemen_GO_mac"
	;;
	linux*) 
		BINARY_NAME="Ikemen_GO_linux" 
	;;
	*)
		BINARY_NAME="Ikemen_GO_linux"
	;;
esac
```

Now I get this brand new error when trying to compile (which Googling around didn't solve at all):

```cmd
pi@raspberrypi:~/Desktop/Stuff/Ikemen-GO/build $ sudo ./build_cmpt.sh 
# github.com/Windblade-GR01/Ikemen_GO/src/src
/usr/lib/go-1.11/pkg/tool/linux_arm/link: running gcc failed: exit status 1
/tmp/go-link-774418994/000000.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
 
chmod: cannot access './bin/Ikemen_GO_linux': No such file or directory
```

Not even sure what exactly is causing this one; this was installed on a fresh copy of Raspbian and the only commands I've ran were ones to get from fresh-install to compiling IKEMEN (namely, installing dependencies via `sudo apt install`, a couple `mkdir`s,  a `git clone`, and `sudo ./get.sh` and `sudo ./build_cmpt.sh`).  Is the Pi 4 distribution of Golang simply broken?

**Comment by SuperFromND** [comment]
Closing this issue as it's been recently solved by some of joamjoamjoam's PRs.
