### ISSUE TITLE
[Arch] Can't loads motif

### ISSUE THREAD

**Issue by TK4E** [Windblade-GR01/Ikemen-GO#186]
```
wget -c "https://ci.appveyor.com/api/buildjobs/xm8u7620oum9uf80/artifacts/bin%2Frelease%2FIkemen_GO_Linux.zip"
unzip *
./Ikemen_GO_linux -r mugen1

```

<details>
<summary>output</summary>

```

ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fc621727664]

runtime stack:
runtime.throw(0xdd498a, 0x2a)
        /usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xba2880, 0xc000d317c0, 0x2198390)
        /usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc000d31790 sp=0xc000d31758 pc=0x4b83eb
github.com/gotk3/gotk3/gtk._Cfunc_gtk_dialog_run(0x2198390, 0x0)
        _cgo_gotypes.go:8407 +0x49 fp=0xc000d317c0 sp=0xc000d31790 pc=0x759f89
github.com/gotk3/gotk3/gtk.(*Dialog).Run.func1(0xc000c5a7d0, 0x21c1170)
        /code/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:2963 +0x64 fp=0xc000d31800 sp=0xc000d317c0 pc=0x7f5194
github.com/gotk3/gotk3/gtk.(*Dialog).Run(0xc000c5a7d0, 0xdbe8d1)
        /code/go/pkg/mod/github.com/gotk3/gotk3@v0.4.0/gtk/gtk.go:2963 +0x2b fp=0xc000d31820 sp=0xc000d31800 pc=0x7ab98b
github.com/sqweek/dialog.(*MsgBuilder).error(0xc000d31ca8)
        /code/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200601143742-43ea34326190/dlgs_linux.go:41 +0x1a7 fp=0xc000d318f8 sp=0xc000d31820 pc=0x9308e7
github.com/sqweek/dialog.(*MsgBuilder).Error(...)
        /code/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200601143742-43ea34326190/dlgs.go:61
main.main()
        /code/src/main.go:487 +0x258f fp=0xc000d31f60 sp=0xc000d318f8 pc=0xab6f2f
runtime.main()
        /usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc000d31fe0 sp=0xc000d31f60 pc=0x4e4f2e
runtime.goexit()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000d31fe8 sp=0xc000d31fe0 pc=0x5100f1

goroutine 18 [sleep]:
runtime.goparkunlock(...)
        /usr/lib/go-1.13/src/runtime/proc.go:310
time.Sleep(0x989680)
        /usr/lib/go-1.13/src/runtime/time.go:105 +0x157
main.(*System).soundWrite(0x168a880)
        /code/src/system.go:638 +0x3e2
created by main.(*System).audioOpen
        /code/src/system.go:626 +0xd6

goroutine 6 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc0002f4000, 0x1000, 0xc0000484e8, 0x800000, 0x4e233a)
        /usr/lib/go-1.13/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc0002f4000, 0x1000, 0x1000, 0x0, 0x4c1466, 0x7fc621b576d0)
        /usr/lib/go-1.13/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
        /usr/lib/go-1.13/src/syscall/syscall_unix.go:183
internal/poll.(*FD).Read(0xc000070060, 0xc0002f4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.13/src/internal/poll/fd_unix.go:165 +0x164
os.(*File).read(...)
        /usr/lib/go-1.13/src/os/file_unix.go:259
os.(*File).Read(0xc000012010, 0xc0002f4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.13/src/os/file.go:116 +0x71
bufio.(*Scanner).Scan(0xc000048748, 0x0)
        /usr/lib/go-1.13/src/bufio/scan.go:213 +0xa4
main.(*System).init.func1(0x168a880)
        /code/src/system.go:523 +0x105
created by main.(*System).init
        /code/src/system.go:521 +0x654


```
</details>

**Comment by TK4E** [comment]
```sh
ln -s font.ttf /usr/share/fonts/arial.ttf
fc-cache -fv
MESA_GL_VERSION_OVERRIDE=4.4 ./Ikemen_GO_Linux -r mugen1
```
