### ISSUE TITLE
Ubuntu Build: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f2c8e357fc4]

### ISSUE THREAD

**Issue by formula1** [Windblade-GR01/Ikemen-GO#222]
At first I was running into the issue
```
user@system76-pc:~/Games/Ikemen_GO/build$ bash ./build_cmpt.sh 
cp: cannot stat './script/': No such file or directory
```

But I created a `script` directory in the `build` parent directory

i extracted https://github.com/Windblade-GR01/Ikemen_GO-Elecbyte-Screenpack into the `./bin` folder

but Now I'm running into 
```
sam@system76-pc:~/Games/Ikemen_GO/bin$ bash Ikemen_GO.command 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f07157d5fc4]

runtime stack:
runtime.throw(0xa0764d, 0x2a)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8b6150, 0xc0001b3700, 0x0)
	/usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc0001b36d0 sp=0xc0001b3698 pc=0x44a32b
github.com/sqweek/dialog._Cfunc_gtk_dialog_run(0x21e0300, 0x0)
	_cgo_gotypes.go:229 +0x49 fp=0xc0001b3700 sp=0xc0001b36d0 pc=0x642be9
github.com/sqweek/dialog.runMsgDlg.func4(0x21e0300, 0x1fa1fe0)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:39 +0x56 fp=0xc0001b3738 sp=0xc0001b3700 pc=0x643666
github.com/sqweek/dialog.runMsgDlg(0x9e9d9c, 0x5, 0x300000000, 0x1, 0xc0001b3c60, 0xc000000000)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:39 +0x217 fp=0xc0001b3850 sp=0xc0001b3738 pc=0x6432c7
github.com/sqweek/dialog.(*MsgBuilder).error(...)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:51
github.com/sqweek/dialog.(*MsgBuilder).Error(...)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs.go:61
main.main()
	/home/sam/Games/Ikemen_GO/src/main.go:580 +0x27b1 fp=0xc0001b3f60 sp=0xc0001b3850 pc=0x7c7d01
runtime.main()
	/usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc0001b3fe0 sp=0xc0001b3f60 pc=0x47687e
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001b3fe8 sp=0xc0001b3fe0 pc=0x4a1851

```

**Comment by juanibiapina** [comment]
I get the same thing on nixos. I can provide an exact list of dependencies I used if needed.

**Comment by juanibiapina** [comment]
I just noticed a log file with the following output. I don't know if it's related but I'll try to fix it and see what happens.
```
external/script/main.lua:24: 
File doesn't exist: data/system.def
stack traceback:
	[G]: in function 'panicError'
	external/script/main.lua:24: in function 'f_fileRead'
	external/script/main.lua:339: in main chunk
	[G]: ?
```

**Comment by juanibiapina** [comment]
Indeed this is caused by a bunch os missing files. You can get those files from the final release distribution in Appveyor.

**Comment by formula1** [comment]
This worked but I'd prefer to be able to build from source if possible

```
git clone -q --branch=main https://github.com/K4thos/Ikemen_GO.git ~/Games/ikemen-go
cd ~/Games/ikemen-go
mkdir bin
mkdir bin/release
cd build
sh ./appveyor_docker_build.sh
sh ./appveyor_pack_release.sh https://github.com/K4thos/Ikemen_GO-Elecbyte-Screenpack.git
cd ..
export CGO_ENABLED=1
CGO_ENABLED=1
echo ------------------------------------------------------------
echo 'Building linux binary...'
echo ------------------------------------------------------------
go build -i -tags al_cmpt -o ./bin/Ikemen_GO_linux ./src

cd ./bin
bash Ikemen_GO.command
```

**Comment by juanibiapina** [comment]
You have built it from source. It's exploding when running. You should get the extra files from the final distribution. My guess is that they're not available in the repo because they're copyright protected.

**Comment by Windblade-GR01** [comment]
Oh just found out this issue.
It was a problem with a folder rename that did break build scripts.
It has been fixed some time ago.
