### ISSUE TITLE
Cannot add Character

### ISSUE THREAD

**Issue by formula1** [Windblade-GR01/Ikemen-GO#223]
After downloading this character https://mugenarchive.com/forums/downloads.php?do=file&id=68-ryu-gm
adding it to the ./bin/chars
then adding it to the ./in/data/select.dev

I run into an error

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7ffba508bfc4]

runtime stack:
runtime.throw(0xa03117, 0x2a)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib/go-1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8b2700, 0xc0003fb700, 0x0)
	/usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc0003fb6d0 sp=0xc0003fb698 pc=0x44a32b
github.com/sqweek/dialog._Cfunc_gtk_dialog_run(0x5332300, 0x0)
	_cgo_gotypes.go:229 +0x49 fp=0xc0003fb700 sp=0xc0003fb6d0 pc=0x642be9
github.com/sqweek/dialog.runMsgDlg.func4(0x5332300, 0x5357e50)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:39 +0x56 fp=0xc0003fb738 sp=0xc0003fb700 pc=0x643666
github.com/sqweek/dialog.runMsgDlg(0x9e595c, 0x5, 0x300000000, 0x1, 0xc0003fbc40, 0xc000000000)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:39 +0x217 fp=0xc0003fb850 sp=0xc0003fb738 pc=0x6432c7
github.com/sqweek/dialog.(*MsgBuilder).error(...)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs_linux.go:51
github.com/sqweek/dialog.(*MsgBuilder).Error(...)
	/home/sam/go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200911184034-8a3d98e8211d/dlgs.go:61
main.main()
	/home/sam/Games/ikemen-go-appveyor/src/main.go:594 +0x264b fp=0xc0003fbf60 sp=0xc0003fb850 pc=0x7c414b
runtime.main()
	/usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc0003fbfe0 sp=0xc0003fbf60 pc=0x47687e
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0003fbfe8 sp=0xc0003fbfe0 pc=0x4a1851

goroutine 18 [sleep]:
runtime.goparkunlock(...)
	/usr/lib/go-1.13/src/runtime/proc.go:310
time.Sleep(0x989680)
	/usr/lib/go-1.13/src/runtime/time.go:105 +0x157
main.(*System).soundWrite(0xd98940)
	/home/sam/Games/ikemen-go-appveyor/src/system.go:661 +0x3e2
created by main.(*System).audioOpen
	/home/sam/Games/ikemen-go-appveyor/src/system.go:649 +0xd6

goroutine 19 [syscall]:
github.com/hajimehoshi/oto._Cfunc_snd_pcm_writei(0x1f2a1c0, 0xc001d89a80, 0x5be, 0x0)
	_cgo_gotypes.go:173 +0x4e
github.com/hajimehoshi/oto.(*driver).TryWrite.func1(0xc0001d4040, 0xc000256000)
	/home/sam/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/driver_linux.go:143 +0x125
github.com/hajimehoshi/oto.(*driver).TryWrite(0xc0001d4040, 0xc000256060, 0xa0, 0x8000, 0x0, 0x0, 0x0)
	/home/sam/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/driver_linux.go:143 +0x1d5
github.com/hajimehoshi/oto.(*driverWriter).Write(0xc000202000, 0xc000256000, 0x100, 0x8000, 0x0, 0x0, 0x0)
	/home/sam/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:148 +0x11f
io.copyBuffer(0xab3de0, 0xc000202000, 0xab3e00, 0xc0001d4080, 0xc000256000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.13/src/io/io.go:404 +0x1fb
io.Copy(...)
	/usr/lib/go-1.13/src/io/io.go:364
github.com/hajimehoshi/oto.NewContext.func1(0xc000206000)
	/home/sam/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:85 +0x69
created by github.com/hajimehoshi/oto.NewContext
	/home/sam/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/context.go:84 +0x291

goroutine 20 [select]:
io.(*pipe).Write(0xc00020a000, 0xc0001f2e90, 0x1658, 0x1658, 0x2e90, 0x0, 0x0)
	/usr/lib/go-1.13/src/io/pipe.go:87 +0x1fb
io.(*PipeWriter).Write(0xc0001d6068, 0xc0001f0000, 0x44e8, 0x44e8, 0x113a, 0x1, 0x0)
	/usr/lib/go-1.13/src/io/pipe.go:153 +0x4c
github.com/hajimehoshi/oto.(*Player).Write(...)
	/home/sam/go/pkg/mod/github.com/hajimehoshi/oto@v0.5.4/player.go:60
github.com/faiface/beep/speaker.update()
	/home/sam/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:129 +0x1b3
github.com/faiface/beep/speaker.Init.func1()
	/home/sam/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:52 +0x24
created by github.com/faiface/beep/speaker.Init
	/home/sam/go/pkg/mod/github.com/faiface/beep@v1.0.2/speaker/speaker.go:48 +0x1fe

goroutine 21 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc00038c000, 0x1000, 0xc000043ce8, 0x800000, 0x473c8a)
	/usr/lib/go-1.13/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc00038c000, 0x1000, 0x1000, 0x0, 0x4532d6, 0x7ffba38bd460)
	/usr/lib/go-1.13/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(...)
	/usr/lib/go-1.13/src/syscall/syscall_unix.go:183
internal/poll.(*FD).Read(0xc0000240c0, 0xc00038c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.13/src/internal/poll/fd_unix.go:165 +0x164
os.(*File).read(...)
	/usr/lib/go-1.13/src/os/file_unix.go:259
os.(*File).Read(0xc000010010, 0xc00038c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.13/src/os/file.go:116 +0x71
bufio.(*Scanner).Scan(0xc000043f48, 0x0)
	/usr/lib/go-1.13/src/bufio/scan.go:213 +0xa4
main.(*System).init.func1(0xd98940)
	/home/sam/Games/ikemen-go-appveyor/src/system.go:546 +0x105
created by main.(*System).init
	/home/sam/Games/ikemen-go-appveyor/src/system.go:544 +0x684

```

**Comment by Orochikyocr** [comment]
Your post makes little sense.
First there no such thing as bin/chars.
Chars folder is on the root folder of Ikemen Go.
./in/data/select.dev
Yo mean select.def? Where that /in/ came from? Are you in MAC?
Check the ikemen.log file for the right debug info. 
Start your Ikemen Go, let it crash to desktop, then check ikemen.log which is in the root folder.

**Comment by K4thos** [comment]
tested - linked character loaded fine for me. There is no enough info to reproduce it.
